sudo: required
services:
    - docker
before_install:
    - docker build -t usmanmaqbool636/docker-react -f Dockerfile.dev .
script:
    - docker run usmanmaqbool636/docker-react set CI=true && npm run test -- --coverage